name: Core unit/functional tests

on: push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8

      - name: Install core dependencies
        run: |
          conda install -y -c conda-forge metview-batch

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv dependencies
        run: |
          pip install wheel
          pip install pipenv pip setuptools
          pipenv sync --dev

      - name: Run core unit/functional tests
        run: |
          source $(conda info --base)/bin/activate
          pipenv run test --cov=./core --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
