name: Electron unit tests

on: push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.5.0'

      - name: Install dependencies
        run: yarn --dev

      - name: Run Jest tests
        run: yarn test
